<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>

    <RootNamespace>BattleNetSwitcher</RootNamespace>
    <AssemblyName>BattleNetSwitcher</AssemblyName>

    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>app.ico</ApplicationIcon>

    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ApplicationDefaultFont>Microsoft YaHei UI, 9pt</ApplicationDefaultFont>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BattleNetSwitcher.Core\BattleNetSwitcher.Core.csproj" />
  </ItemGroup>

</Project>
